baseURL = ''
languageCode = 'en-us'
title = 'blueturtle.dev'
theme = 'archie'
pygmentsstyle = "borland"
pygmentscodefences = false
pygmentscodefenceguesssyntax = true
paginate = 5

[params]
mode = "toggle"
useCDN = false
subtitle = "observe, think, learn, action, reflect"
mathjax = true
katex = true
author = "tarmacChen"

[markup.highlight]
lineNos = true
tabWidth = 2
hl_Lines = ""
noClasses = true

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Cards"
url = "/cards"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 1
